[project]
name = "dog-nutrition-ai"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = ""},
]
dependencies = ["langchain>=0.3.27", "langgraph>=0.6.8", "langchain-mcp-adapters>=0.1.10", "langchain-ollama>=0.3.8", "langgraph-cli>=0.4.3", "langgraph-api>=0.4.38", "langgraph-sdk>=0.2.9", "langchain-community>=0.3.31", "ddgs>=9.6.1"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.scripts]
mcp = "mcp/server.py"
agent = "agent/agent.py"
server = "python -m langgraph_cli dev"

[tool.pdm]
distribution = false
